# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

Link: <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
# np.show_config()

1.16.4


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
a = np.zeros((3, 4))
print("%d bytes" %(a.size * a.itemsize)) # 12 * 8

96 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
a = np.arange(10)
a = a[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
a = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [22]:
a = np.random.random((3, 3, 3))
a

array([[[0.7032576 , 0.92935651, 0.72550297],
        [0.18002932, 0.99367194, 0.32983679],
        [0.66913099, 0.83214689, 0.53009953]],

       [[0.93668638, 0.2144665 , 0.7652716 ],
        [0.70886605, 0.48453995, 0.19971347],
        [0.38312039, 0.91217623, 0.449788  ]],

       [[0.81411305, 0.70308434, 0.48982084],
        [0.4862641 , 0.85453703, 0.39440235],
        [0.11419796, 0.74931989, 0.60023471]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
a = np.random.random((10, 10))
a_min, a_max = a.min(), a.max()
print(a_min, a_max)

0.00167922257434161 0.9945404427824838


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [2]:
a = np.random.random(30)
a.mean()

0.5338848207380114

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [3]:
a = np.ones((4, 4))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [4]:
a = np.ones((4, 4))
np.pad(a, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
# fancy indexing, not padding
a = np.ones((4, 4))
a[:, [0, -1]] = 0
a[[0, -1]] = 0
a

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan # nan
np.nan == np.nan # Flase
np.inf > np.nan # False
np.nan - np.nan # nan
np.nan in set([np.nan]) # True
0.3 == 3 * 0.1 # False
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [16]:
a = np.diag([1, 2, 3, 4], k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
a = np.zeros((8, 8), dtype=int)
a[::2, 1::2] = 1
a[1::2, ::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [19]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
a = np.tile([[1, 0], [0, 1]], (4, 4))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
a = np.arange(1, 17).reshape(4, 4)
(a - np.mean(a)) / np.std(a)

array([[-1.62697843, -1.41004798, -1.19311752, -0.97618706],
       [-0.7592566 , -0.54232614, -0.32539569, -0.10846523],
       [ 0.10846523,  0.32539569,  0.54232614,  0.7592566 ],
       [ 0.97618706,  1.19311752,  1.41004798,  1.62697843]])

In [24]:
a.mean()

8.5

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [55]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [58]:
a = np.ones((5, 3))
b = np.ones((3, 2))
print(np.dot(a, b))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [62]:
# fancy indexing
a = np.arange(11)
a[(3 < a) & (a < 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [64]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [80]:
a = np.arange(5)
print(a**a)
print(2 << a >> 2)
print(a <- a)
print(1j * a)
print(a / 1 / 1)
# print(a<a>a) illegal

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [88]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [96]:
a = np.random.uniform(-5, 5, 5)
print(a)
print(np.where(a>0, np.ceil(a), np.floor(a)))

[-1.73942579 -2.66530738 -0.85366192 -0.41863913  2.72181354]
[-2. -3. -1. -1.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [98]:
a = np.random.randint(0, 10, 10)
b = np.random.randint(0, 10, 10)
print(a)
print(b)
print(np.intersect1d(a, b))

[4 7 0 2 5 1 8 0 2 0]
[9 8 0 0 3 7 9 4 9 0]
[0 4 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [100]:
# Suicide mode on
defaults = np.seterr(all="ignore")
a = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [106]:
np.sqrt(-1) == np.emath.sqrt(-1) # nan == ij

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [110]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-12-15 2020-12-16 2020-12-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [114]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [117]:
A = np.ones(3) * 1
B = np.ones(3) * 2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [3]:
a = np.random.uniform(0, 10, 10)
print(a)
print(a - a % 1)
print(a // 1)
print(np.floor(a))
print(a.astype(int))
print(np.trunc(a))

[2.61530425 0.26975726 8.57740641 7.7886895  5.20134552 2.92877795
 0.94762933 4.89537123 4.79328257 8.87406254]
[2. 0. 8. 7. 5. 2. 0. 4. 4. 8.]
[2. 0. 8. 7. 5. 2. 0. 4. 4. 8.]
[2. 0. 8. 7. 5. 2. 0. 4. 4. 8.]
[2 0 8 7 5 2 0 4 4 8]
[2. 0. 8. 7. 5. 2. 0. 4. 4. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [19]:
# a = np.tile(np.arange(5), (5, 1))
a = np.zeros((5, 5), dtype=int)
a += np.arange(5)
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [20]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(), dtype=float, count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [33]:
a = np.linspace(0, 1, num=11, endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [38]:
a = np.random.random(10)
a.sort()
print(a)

[0.19259291 0.29535873 0.37722968 0.58343073 0.60272832 0.6593489
 0.67313961 0.76166939 0.80629073 0.94445527]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
a = np.arange(5)
np.add.reduce(a)

10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [46]:
a = np.random.randint(0, 2, 5)
b = np.random.randint(0, 2, 5)
# print(np.allclose(a, b))
print(np.array_equal(a, b))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [49]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1 # error

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [54]:
a = np.random.random((10, 2))
x, y = a[:, 0], a[:, 1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y, x)
print(r)
print(t)

[0.34032514 0.65890935 0.61279767 1.10998548 0.91211703 0.83538401
 0.16904673 0.57933523 0.79794342 0.75641645]
[0.55751437 1.1650366  0.69666967 0.87008472 1.12544106 0.11592062
 0.31680192 0.1207747  0.41875367 1.31556635]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [59]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.23022588 0.52355792 0.31025149 0.56753107 0.11564288 0.3382035
 0.50039634 0.2485599  0.         0.30043361]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [63]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [66]:
a = np.arange(8)
b = a + 0.5
C = 1.0 / np.subtract.outer(a, b) # a[:, None] - b, broadcasting
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [69]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [71]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


In [78]:
np.set_printoptions(threshold=float("inf"))
a = np.zeros((5, 5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [81]:
a = np.arange(100)
v = np.random.uniform(0, 100)
idx = (np.abs(a - v).argmin())
print(a[idx])

57


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [84]:
a = np.zeros(5, [
    ('position', [('x', float, 1), ('y', float, 1)]),
    ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])
])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (10,2) representing coordinates, find point by point distances (★★☆)

In [18]:
a = np.random.random((10, 2))
x, y = np.atleast_2d(a[:, 0], a[:, 1])
D = np.sqrt((x - x.T)**2 + (y - y.T)**2)
print(D)

[[0.         0.8677722  0.63716858 0.74306062 0.42438004 0.1898905
  0.0494321  0.40200206 0.22512946 0.31968338]
 [0.8677722  0.         0.46206024 0.30775181 1.04058671 0.86369264
  0.91487546 0.66213658 0.72701021 0.55421557]
 [0.63716858 0.46206024 0.         0.1696942  0.63675612 0.73442644
  0.68540727 0.27287687 0.62413151 0.4438035 ]
 [0.74306062 0.30775181 0.1696942  0.         0.79970852 0.80625623
  0.79246354 0.424721   0.6808812  0.48921417]
 [0.42438004 1.04058671 0.63675612 0.79970852 0.         0.61391677
  0.43270389 0.38062623 0.62526623 0.6148959 ]
 [0.1898905  0.86369264 0.73442644 0.80625623 0.61391677 0.
  0.18718915 0.54281587 0.13669093 0.32224223]
 [0.0494321  0.91487546 0.68540727 0.79246354 0.43270389 0.18718915
  0.         0.44595187 0.25119895 0.36438682]
 [0.40200206 0.66213658 0.27287687 0.424721   0.38062623 0.54281587
  0.44595187 0.         0.46818555 0.346013  ]
 [0.22512946 0.72701021 0.62413151 0.6808812  0.62526623 0.13669093
  0.25119895 0.468185

In [20]:
import scipy
from scipy import spatial
a = np.random.random((10, 2))
D = scipy.spatial.distance.cdist(a, a)
print(D)

[[0.         0.62227466 0.29505015 0.35590177 0.83802585 0.20722352
  0.86671409 0.79510807 0.67654449 0.60059499]
 [0.62227466 0.         0.82706733 0.61506043 0.65542021 0.62221967
  0.65432633 0.49112344 0.75057986 0.44801074]
 [0.29505015 0.82706733 0.         0.29383946 0.80856614 0.20659874
  0.84539404 0.83196328 0.55876006 0.63073692]
 [0.35590177 0.61506043 0.29383946 0.         0.5231397  0.15369661
  0.55811252 0.53834569 0.32097728 0.33813892]
 [0.83802585 0.65542021 0.80856614 0.5231397  0.         0.66588143
  0.04058682 0.18422381 0.30423239 0.2563398 ]
 [0.20722352 0.62221967 0.20659874 0.15369661 0.66588143 0.
  0.69866632 0.65668009 0.4737806  0.4539613 ]
 [0.86671409 0.65432633 0.84539404 0.55811252 0.04058682 0.69866632
  0.         0.17017209 0.34478187 0.27621721]
 [0.79510807 0.49112344 0.83196328 0.53834569 0.18422381 0.65668009
  0.17017209 0.         0.42509659 0.20290876]
 [0.67654449 0.75057986 0.55876006 0.32097728 0.30423239 0.4737806
  0.34478187 0.425096

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [3]:
a = (np.random.rand(5) * 100).astype('float32')
print(a)
b = a.view('int32')
b[:] = a
print(b)

[54.275837 49.729053 78.12459  30.417345 75.532524]
[54 49 78 30 75]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [4]:
from io import StringIO
# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')

a = np.genfromtxt(s, delimiter=',', dtype='int')
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [14]:
a = np.arange(8).reshape(2, 2, 2)
for idx, val in np.ndenumerate(a):
    print(idx, val)

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7


In [15]:
a = np.arange(8).reshape(2, 2, 2)
for idx in np.ndindex(a.shape):
    print(idx, a[idx])

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [19]:
X, Y = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5))
D = np.sqrt(X * X + Y * Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu)**2 / (2.0 * sigma**2)))
print(G)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [64]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


In [31]:
a = np.zeros((5, 5))
np.put(a, np.random.choice(range(25), 7, replace=False), -1)
print(a)

[[ 0.  0. -1. -1.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1. -1. -1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [44]:
a = np.random.rand(3, 2)
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[ 0.03162633 -0.03162633]
 [-0.18722484  0.18722484]
 [ 0.29922399 -0.29922399]]


#### 59. How to sort an array by the nth column? (★★☆)

In [49]:
def sort_nth_column(arr, n):
    print(arr[arr[:, n].argsort()])

a = np.random.randint(0, 10, (3, 3))
print(a)
sort_nth_column(a, 2)

[[5 7 9]
 [9 7 1]
 [3 6 5]]
[[9 7 1]
 [3 6 5]
 [5 7 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [62]:
a = np.random.randint(0, 3, (3, 10))
print(a)
print((~a.any(axis=0)).any())

[[0 1 1 0 1 0 2 2 1 0]
 [0 2 2 1 0 1 2 1 1 2]
 [1 0 0 0 0 1 1 2 2 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [72]:
a = np.random.uniform(0, 1, 10)
val = 0.5
print(a[np.abs(a - val).argmin()])
print(a.flat[np.abs(a - val).argmin()])

0.48813294767078486
0.48813294767078486


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [86]:
a = np.arange(3).reshape(3, 1)
b = np.arange(3).reshape(1, 3)
it = np.nditer([a, b, None])
for x, y, z in it:
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [15]:
class NamedArray:
    def __init__(self, array, name="no name"):
        self.array = array
        self.name = name
        
a = NamedArray(np.arange(5), "array")
a.name

'array'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [21]:
a = np.arange(7)
b = np.random.randint(0, len(a), 10)
print(a)
print(b)
a += np.bincount(b, minlength=len(a))
print(a)

[0 1 2 3 4 5 6]
[1 3 2 1 4 3 2 4 6 5]
[0 3 4 5 6 6 7]


In [22]:
a = np.arange(7)
b = np.random.randint(0, len(a), 10)
print(a)
print(b)
np.add.at(a, b, 1)
print(a)

[0 1 2 3 4 5 6]
[6 6 5 0 6 2 4 3 4 1]
[1 2 3 4 6 6 9]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [27]:
w = [1, 2, 3, 4, 5, 6]
a = [1, 3, 9, 3, 4, 1]
np.bincount(a, w)

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [30]:
answer(66)

# Author: Nadav Horesh

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))


In [38]:
w, h = 16, 16
img = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [45]:
a = np.random.randint(0,10,(3,4,3,4))
a.sum(axis=(-2, -1))

array([[53, 55, 69, 61],
       [45, 59, 51, 42],
       [66, 47, 61, 66]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [47]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)
D_cnt = np.bincount(S)
D_means = D_sums / D_cnt
D_means

array([0.48645064, 0.39506837, 0.49872414, 0.61573248, 0.60185927,
       0.43898614, 0.58703032, 0.58469908, 0.56803134, 0.54201175])

In [48]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)

import pandas as pd
pd.Series(D).groupby(S).mean()

0    0.666934
1    0.500473
2    0.552992
3    0.384359
4    0.416544
5    0.582614
6    0.507637
7    0.460651
8    0.393291
9    0.465834
dtype: float64

#### 69. How to get the diagonal of a dot product? (★★★)

In [51]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [52]:
np.diag(np.dot(A, B))

array([2.33593045, 0.74940205, 1.51097816, 1.5626401 , 1.18076451])

In [54]:
np.sum(A * B.T, axis=1)

array([2.33593045, 0.74940205, 1.51097816, 1.5626401 , 1.18076451])

In [55]:
np.einsum("ij,ji->i", A, B)

array([2.33593045, 0.74940205, 1.51097816, 1.5626401 , 1.18076451])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [57]:
a = np.array([1, 2, 3, 4, 5])
b = np.zeros(len(a) + (len(a) - 1) * 3)
b[::4] = a
b

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [8]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
A * B[:, :, None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [18]:
A = np.arange(9).reshape(3, 3)
A[[0, 1]] = A[[1, 0]]
A

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [21]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
G

array([( 0,  0), ( 0, 20), ( 0, 24), ( 5, 34), ( 5, 92), ( 6, 23),
       ( 6, 46), ( 9, 19), ( 9, 74), (13, 47), (13, 63), (16, 62),
       (16, 91), (19, 74), (20, 20), (23, 46), (25, 46), (25, 62),
       (34, 92), (46, 62), (47, 63), (57, 88), (57, 89), (62, 91),
       (66, 82), (66, 96), (82, 96), (88, 89)],
      dtype=[('p0', '<i4'), ('p1', '<i4')])

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [23]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [24]:
answer(75)

# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


In [27]:
def moving_average(arr, siz=3):
    ret = np.cumsum(arr, dtype=float)
    ret[siz:] = ret[siz:] - ret[:-siz]
    return ret[siz - 1:] / siz

a = np.arange(10)
moving_average(a, 3)

array([1., 2., 3., 4., 5., 6., 7., 8.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [29]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)
Z

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [38]:
Z = np.random.randint(0, 2, 15)
np.logical_not(Z, out=Z)

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0])

In [39]:
Z = np.random.uniform(-1.0, 1.0, 10)
np.negative(Z, out=Z)

array([ 0.86234616, -0.63159061, -0.78619596,  0.54835921, -0.38714587,
        0.13113228,  0.67649739, -0.09505436,  0.07443836,  0.97265682])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [41]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
distance(P0, P1, p)

array([8.29609164, 1.62856786, 1.65977393, 9.87352905, 7.56494832,
       8.27955812, 7.9112861 , 6.56168485, 4.09622518, 1.64744529])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [42]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
P = np.random.uniform(-10, 10, (10,2))
np.array([distance(P0, P1, P) for p in P])

array([[ 6.93252781,  2.76522873,  3.92739395,  4.67500125,  1.14992712,
         7.42997443,  2.70276382,  7.68639056,  4.87823663, 12.27819968],
       [ 6.93252781,  2.76522873,  3.92739395,  4.67500125,  1.14992712,
         7.42997443,  2.70276382,  7.68639056,  4.87823663, 12.27819968],
       [ 6.93252781,  2.76522873,  3.92739395,  4.67500125,  1.14992712,
         7.42997443,  2.70276382,  7.68639056,  4.87823663, 12.27819968],
       [ 6.93252781,  2.76522873,  3.92739395,  4.67500125,  1.14992712,
         7.42997443,  2.70276382,  7.68639056,  4.87823663, 12.27819968],
       [ 6.93252781,  2.76522873,  3.92739395,  4.67500125,  1.14992712,
         7.42997443,  2.70276382,  7.68639056,  4.87823663, 12.27819968],
       [ 6.93252781,  2.76522873,  3.92739395,  4.67500125,  1.14992712,
         7.42997443,  2.70276382,  7.68639056,  4.87823663, 12.27819968],
       [ 6.93252781,  2.76522873,  3.92739395,  4.67500125,  1.14992712,
         7.42997443,  2.70276382,  7.68639056

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [44]:
# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 9 3 7 0 7 9 3 3 2]
 [0 7 2 2 3 0 8 6 1 8]
 [2 6 4 8 3 6 4 2 7 1]
 [3 8 1 2 2 1 7 2 6 8]
 [0 7 2 5 2 9 5 7 3 3]
 [8 4 2 1 7 1 1 5 4 1]
 [4 1 0 2 7 6 6 9 5 3]
 [1 9 2 8 5 9 1 3 9 9]
 [9 3 9 1 8 8 0 7 8 7]
 [2 5 6 7 8 2 8 1 6 0]]
[[0 0 0 0 0]
 [0 8 9 3 7]
 [0 0 7 2 2]
 [0 2 6 4 8]
 [0 3 8 1 2]]


E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [46]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [51]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [60]:
a = np.random.randint(0, 9, 20)
np.bincount(a).argmax()

6

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [62]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 4 2]
   [1 1 4]
   [1 3 4]]

  [[4 2 0]
   [1 4 4]
   [3 4 4]]

  [[2 0 3]
   [4 4 0]
   [4 4 0]]

  [[0 3 2]
   [4 0 2]
   [4 0 4]]

  [[3 2 2]
   [0 2 3]
   [0 4 4]]

  [[2 2 4]
   [2 3 3]
   [4 4 3]]

  [[2 4 2]
   [3 3 1]
   [4 3 3]]

  [[4 2 2]
   [3 1 4]
   [3 3 0]]]


 [[[1 1 4]
   [1 3 4]
   [1 2 0]]

  [[1 4 4]
   [3 4 4]
   [2 0 4]]

  [[4 4 0]
   [4 4 0]
   [0 4 0]]

  [[4 0 2]
   [4 0 4]
   [4 0 2]]

  [[0 2 3]
   [0 4 4]
   [0 2 1]]

  [[2 3 3]
   [4 4 3]
   [2 1 1]]

  [[3 3 1]
   [4 3 3]
   [1 1 4]]

  [[3 1 4]
   [3 3 0]
   [1 4 2]]]


 [[[1 3 4]
   [1 2 0]
   [0 1 4]]

  [[3 4 4]
   [2 0 4]
   [1 4 1]]

  [[4 4 0]
   [0 4 0]
   [4 1 2]]

  [[4 0 4]
   [4 0 2]
   [1 2 3]]

  [[0 4 4]
   [0 2 1]
   [2 3 1]]

  [[4 4 3]
   [2 1 1]
   [3 1 4]]

  [[4 3 3]
   [1 1 4]
   [1 4 0]]

  [[3 3 0]
   [1 4 2]
   [4 0 4]]]


 [[[1 2 0]
   [0 1 4]
   [4 2 0]]

  [[2 0 4]
   [1 4 1]
   [2 0 4]]

  [[0 4 0]
   [4 1 2]
   [0 4 1]]

  [[4 0 2]
   [1 2 3]
   [4 1 1]]

  [[0 2 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [64]:
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  8 15 12  4]
 [ 8  1  9 12  9]
 [15  9  7 42 13]
 [12 12 42  0  8]
 [ 4  9 13  8  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [66]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [68]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [70]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [73]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9997 9998 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [75]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [78]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [81]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.25 s ± 99 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
317 ms ± 4.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
231 ms ± 16.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [83]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [85]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 1 2]
 [1 4 1]
 [3 3 2]
 [2 2 3]
 [0 4 3]
 [3 2 0]
 [1 3 2]
 [1 2 2]
 [1 0 1]
 [2 3 1]]
[[2 1 2]
 [1 4 1]
 [3 3 2]
 [2 2 3]
 [0 4 3]
 [3 2 0]
 [1 3 2]
 [1 2 2]
 [1 0 1]
 [2 3 1]]
[[2 1 2]
 [1 4 1]
 [3 3 2]
 [2 2 3]
 [0 4 3]
 [3 2 0]
 [1 3 2]
 [1 2 2]
 [1 0 1]
 [2 3 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [88]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [90]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 0]
 [1 0 0]
 [1 1 1]]


In [91]:
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 0]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [94]:
A = np.random.uniform(0,1,3)
B = np.random.uniform(0,1,3)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.08655322, 0.20913636, 0.09060068],
       [0.00033434, 0.00080786, 0.00034998],
       [0.08085145, 0.1953593 , 0.08463228]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [4]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [6]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [8]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.07012603  0.29133007]
