In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a[2::]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[2:6]

array([2, 3, 4, 5])

In [6]:
a[2:6:2]

array([2, 4])

In [8]:
a[2:-1]

array([2, 3, 4, 5, 6, 7, 8])

In [7]:
a[2:-1:2]

array([2, 4, 6, 8])

In [20]:
a[::3]

array([0, 3, 6, 9])

In [24]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [25]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
a[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [29]:
a[:,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [31]:
a[::-1, ::-1]

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [32]:
a = np.zeros(16).reshape(4, 4)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
a[1:-1,1:-1] = 1
a

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])